### ISSUE TITLE
Can't see my profile

### ISSUE THREAD

**Issue by FifthSaint** [Bit-Nation/bitnation-web#35]
When I click my 'profile' in the menu top right, I only see white blank. 
![profile](https://cloud.githubusercontent.com/assets/24706270/21409603/868a69fc-c81e-11e6-8c5d-345f726ba472.jpg)
My bitnation name is FifthSaint, same as here. my browser is Chrome and i can see others' profiles.
What will be the reason? I want to have my face! :)

**Comment by FifthSaint** [comment]
And in the menu, 'messages' and 'add posts' are same blank.

**Comment by evok3d** [comment]
We have to refresh the users table every so often, else you are allocated to the wrong user role, which means you cannot see the page. This has been done. Please try again.
