### ISSUE TITLE
https://bitnation.co/join-the-team/ does not load most of the time

### ISSUE THREAD

**Issue by ordex** [Bit-Nation/bitnation-web#39]
90% of the times I try to open the https://bitnation.co/join-the-team/ URL I get a blank page. Reloading several times eventually leads to downloading the page properly. However, even in the latter case it is impossible to submit the form because it will return a blank page again.

**Comment by evok3d** [comment]
@ccmawo can you please look into:
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)

**Comment by evok3d** [comment]
Memory size increased. Issue has been resolved.
